# Generated by Django 6.0.5 on 2026-05-11 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Admin', 'Admin'), ('Pilot', 'Pilot'), ('Customer', 'Customer'), ('General', 'General')], max_length=20, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
            ],
            options={
                'verbose_name': 'site',
                'verbose_name_plural': 'sites',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.group'),
        ),
        migrations.CreateModel(
            name='Geojson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('url', models.TextField(unique=True, verbose_name='URL')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geojsons', to='core.site')),
            ],
            options={
                'verbose_name': 'geojson',
                'verbose_name_plural': 'geojsons',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aws_url', models.CharField(max_length=500, unique=True, verbose_name='AWS URL')),
                ('date', models.DateField(verbose_name='Date')),
                ('pilot', models.CharField(max_length=32, verbose_name='Pilot')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='core.site')),
            ],
            options={
                'verbose_name': 'flight',
                'verbose_name_plural': 'flights',
            },
        ),
    ]
