# Generated by Django 6.0.5 on 2026-05-26 18:00

from django.conf import settings
from django.db import migrations, models


def _ensure_site_fields(apps, schema_editor):
    connection = schema_editor.connection
    introspection = connection.introspection
    with connection.cursor() as cursor:
        table_names = introspection.table_names(cursor)

        def has_column(table_name, column_name):
            if table_name not in table_names:
                return False
            description = introspection.get_table_description(cursor, table_name)
            column_names = [getattr(col, 'name', col[0]) for col in description]
            return column_name in column_names

        if 'core_geojson' in table_names and not has_column('core_geojson', 'level'):
            cursor.execute('ALTER TABLE core_geojson ADD COLUMN level integer NOT NULL DEFAULT 1')

        if 'core_site' in table_names and not has_column('core_site', 'default_style'):
            cursor.execute("ALTER TABLE core_site ADD COLUMN default_style varchar(16) NOT NULL DEFAULT 'split'")

        if 'core_site_allowed_users' not in table_names:
            user_model = apps.get_model(settings.AUTH_USER_MODEL)
            user_table = user_model._meta.db_table
            if connection.vendor == 'sqlite':
                cursor.execute(
                    f'CREATE TABLE core_site_allowed_users ('
                    f' id integer PRIMARY KEY AUTOINCREMENT,'
                    f' site_id integer NOT NULL REFERENCES core_site(id),'
                    f' user_id integer NOT NULL REFERENCES {user_table}(id),'
                    f' UNIQUE(site_id, user_id)'
                    f')'
                )
            else:
                cursor.execute(
                    f'CREATE TABLE core_site_allowed_users ('
                    f' id bigserial PRIMARY KEY,'
                    f' site_id bigint NOT NULL REFERENCES core_site(id) DEFERRABLE INITIALLY DEFERRED,'
                    f' user_id bigint NOT NULL REFERENCES {user_table}(id) DEFERRABLE INITIALLY DEFERRED,'
                    f' UNIQUE(site_id, user_id)'
                    f')'
                )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_group_site_user_group_geojson_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='geojson',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='site',
            name='default_style',
            field=models.CharField(default='split', max_length=16, verbose_name='Default Style'),
        ),
        migrations.AddField(
            model_name='site',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_sites', to=settings.AUTH_USER_MODEL, verbose_name='Allowed Users'),
        ),
        migrations.RunPython(_ensure_site_fields, reverse_code=migrations.RunPython.noop),
    ]
